# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\amg\amg_pipeline\scripts\maya\python\tools\asset_submitter\widgets\submitter_window.ui'
#
# Created: Mon Apr 04 09:25:04 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1214, 964)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1212, 941))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_2 = QtGui.QWidget(self.groupBox_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_objects_btn = QtGui.QPushButton(self.widget_2)
        self.add_objects_btn.setObjectName("add_objects_btn")
        self.horizontalLayout_3.addWidget(self.add_objects_btn)
        self.remove_objects_btn = QtGui.QPushButton(self.widget_2)
        self.remove_objects_btn.setObjectName("remove_objects_btn")
        self.horizontalLayout_3.addWidget(self.remove_objects_btn)
        self.select_objects_btn = QtGui.QPushButton(self.widget_2)
        self.select_objects_btn.setObjectName("select_objects_btn")
        self.horizontalLayout_3.addWidget(self.select_objects_btn)
        self.clear_objects_btn = QtGui.QPushButton(self.widget_2)
        self.clear_objects_btn.setObjectName("clear_objects_btn")
        self.horizontalLayout_3.addWidget(self.clear_objects_btn)
        self.gridLayout_8.addWidget(self.widget_2, 0, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cameras_tab = QtGui.QTabWidget(self.groupBox)
        self.cameras_tab.setObjectName("cameras_tab")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab_8)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.range_start_sbx = QtGui.QSpinBox(self.tab_8)
        self.range_start_sbx.setMinimum(-9999999)
        self.range_start_sbx.setMaximum(999999999)
        self.range_start_sbx.setObjectName("range_start_sbx")
        self.gridLayout.addWidget(self.range_start_sbx, 0, 4, 1, 1)
        self.render_camera_cbb = QtGui.QComboBox(self.tab_8)
        self.render_camera_cbb.setObjectName("render_camera_cbb")
        self.render_camera_cbb.addItem("")
        self.gridLayout.addWidget(self.render_camera_cbb, 0, 2, 1, 1)
        self.range_end_sbx = QtGui.QSpinBox(self.tab_8)
        self.range_end_sbx.setMinimum(-99999999)
        self.range_end_sbx.setMaximum(9999999)
        self.range_end_sbx.setProperty("value", 100)
        self.range_end_sbx.setObjectName("range_end_sbx")
        self.gridLayout.addWidget(self.range_end_sbx, 0, 5, 1, 1)
        self.range_from_btn = QtGui.QPushButton(self.tab_8)
        self.range_from_btn.setObjectName("range_from_btn")
        self.gridLayout.addWidget(self.range_from_btn, 0, 6, 1, 1)
        self.reload_cameras_btn = QtGui.QPushButton(self.tab_8)
        self.reload_cameras_btn.setMaximumSize(QtCore.QSize(50, 10000))
        self.reload_cameras_btn.setObjectName("reload_cameras_btn")
        self.gridLayout.addWidget(self.reload_cameras_btn, 0, 1, 1, 1)
        self.create_new_camera_btn = QtGui.QPushButton(self.tab_8)
        self.create_new_camera_btn.setObjectName("create_new_camera_btn")
        self.gridLayout.addWidget(self.create_new_camera_btn, 0, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout)
        self.cameras_tab.addTab(self.tab_8, "")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtGui.QLabel(self.tab_9)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 1, 2, 1, 1)
        self.sequ_start_spx = QtGui.QSpinBox(self.tab_9)
        self.sequ_start_spx.setObjectName("sequ_start_spx")
        self.gridLayout_9.addWidget(self.sequ_start_spx, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_9)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 1, 4, 1, 1)
        self.sequ_end_spx = QtGui.QSpinBox(self.tab_9)
        self.sequ_end_spx.setObjectName("sequ_end_spx")
        self.gridLayout_9.addWidget(self.sequ_end_spx, 1, 5, 1, 1)
        self.sequencer_rang_btn = QtGui.QPushButton(self.tab_9)
        self.sequencer_rang_btn.setObjectName("sequencer_rang_btn")
        self.gridLayout_9.addWidget(self.sequencer_rang_btn, 1, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 1, 1, 1, 1)
        self.open_sequence_editor_btn = QtGui.QPushButton(self.tab_9)
        self.open_sequence_editor_btn.setObjectName("open_sequence_editor_btn")
        self.gridLayout_9.addWidget(self.open_sequence_editor_btn, 1, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.cameras_tab.addTab(self.tab_9, "")
        self.verticalLayout_12.addWidget(self.cameras_tab)
        self.verticalLayout_17.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_light_preset_cbx = QtGui.QCheckBox(self.groupBox_2)
        self.add_light_preset_cbx.setObjectName("add_light_preset_cbx")
        self.verticalLayout.addWidget(self.add_light_preset_cbx)
        self.renderer_tab_tbw = QtGui.QTabWidget(self.groupBox_2)
        self.renderer_tab_tbw.setObjectName("renderer_tab_tbw")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reload_rig_btn1 = QtGui.QPushButton(self.tab)
        self.reload_rig_btn1.setObjectName("reload_rig_btn1")
        self.verticalLayout_3.addWidget(self.reload_rig_btn1)
        self.light_setup_ai_grp = QtGui.QGroupBox(self.tab)
        self.light_setup_ai_grp.setObjectName("light_setup_ai_grp")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.light_setup_ai_grp)
        self.verticalLayout_22.setSpacing(3)
        self.verticalLayout_22.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtGui.QLabel(self.light_setup_ai_grp)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.ai_use_ground_plane_cbx = QtGui.QCheckBox(self.light_setup_ai_grp)
        self.ai_use_ground_plane_cbx.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ai_use_ground_plane_cbx.setChecked(True)
        self.ai_use_ground_plane_cbx.setObjectName("ai_use_ground_plane_cbx")
        self.gridLayout_6.addWidget(self.ai_use_ground_plane_cbx, 1, 0, 1, 1)
        self.ai_scene_preset_cbb = QtGui.QComboBox(self.light_setup_ai_grp)
        self.ai_scene_preset_cbb.setObjectName("ai_scene_preset_cbb")
        self.ai_scene_preset_cbb.addItem("")
        self.ai_scene_preset_cbb.addItem("")
        self.ai_scene_preset_cbb.addItem("")
        self.ai_scene_preset_cbb.addItem("")
        self.gridLayout_6.addWidget(self.ai_scene_preset_cbb, 0, 1, 1, 1)
        self.ai_render_background_cbx = QtGui.QCheckBox(self.light_setup_ai_grp)
        self.ai_render_background_cbx.setChecked(True)
        self.ai_render_background_cbx.setObjectName("ai_render_background_cbx")
        self.gridLayout_6.addWidget(self.ai_render_background_cbx, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 3, 1, 1)
        self.ai_ground_plane_texture_cbb = QtGui.QComboBox(self.light_setup_ai_grp)
        self.ai_ground_plane_texture_cbb.setObjectName("ai_ground_plane_texture_cbb")
        self.ai_ground_plane_texture_cbb.addItem("")
        self.ai_ground_plane_texture_cbb.addItem("")
        self.ai_ground_plane_texture_cbb.addItem("")
        self.gridLayout_6.addWidget(self.ai_ground_plane_texture_cbb, 1, 1, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addWidget(self.light_setup_ai_grp)
        self.groupBox_11 = QtGui.QGroupBox(self.tab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_23.setSpacing(3)
        self.verticalLayout_23.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.ai_shaders_ly = QtGui.QVBoxLayout()
        self.ai_shaders_ly.setObjectName("ai_shaders_ly")
        self.verticalLayout_23.addLayout(self.ai_shaders_ly)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.verticalLayout_3.setStretch(2, 1)
        self.renderer_tab_tbw.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.reload_rig_btn2 = QtGui.QPushButton(self.tab_2)
        self.reload_rig_btn2.setObjectName("reload_rig_btn2")
        self.verticalLayout_7.addWidget(self.reload_rig_btn2)
        self.light_setup_ogl_grp = QtGui.QGroupBox(self.tab_2)
        self.light_setup_ogl_grp.setObjectName("light_setup_ogl_grp")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.light_setup_ogl_grp)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.light_setup_ogl_grp)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.ogl_scene_preset_cbb = QtGui.QComboBox(self.light_setup_ogl_grp)
        self.ogl_scene_preset_cbb.setObjectName("ogl_scene_preset_cbb")
        self.ogl_scene_preset_cbb.addItem("")
        self.ogl_scene_preset_cbb.addItem("")
        self.gridLayout_3.addWidget(self.ogl_scene_preset_cbb, 0, 1, 1, 1)
        self.ogl_use_ground_plane_cbx = QtGui.QCheckBox(self.light_setup_ogl_grp)
        self.ogl_use_ground_plane_cbx.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ogl_use_ground_plane_cbx.setChecked(True)
        self.ogl_use_ground_plane_cbx.setObjectName("ogl_use_ground_plane_cbx")
        self.gridLayout_3.addWidget(self.ogl_use_ground_plane_cbx, 1, 0, 1, 1)
        self.ogl_ground_plane_texture_cbb = QtGui.QComboBox(self.light_setup_ogl_grp)
        self.ogl_ground_plane_texture_cbb.setObjectName("ogl_ground_plane_texture_cbb")
        self.ogl_ground_plane_texture_cbb.addItem("")
        self.ogl_ground_plane_texture_cbb.addItem("")
        self.ogl_ground_plane_texture_cbb.addItem("")
        self.gridLayout_3.addWidget(self.ogl_ground_plane_texture_cbb, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.light_setup_ogl_grp)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ogl_shaders_ly = QtGui.QVBoxLayout()
        self.ogl_shaders_ly.setObjectName("ogl_shaders_ly")
        self.verticalLayout_6.addLayout(self.ogl_shaders_ly)
        self.verticalLayout_7.addWidget(self.groupBox_9)
        self.verticalLayout_7.setStretch(2, 1)
        self.renderer_tab_tbw.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.renderer_tab_tbw)
        self.verticalLayout_17.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_14.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget = QtGui.QWidget(self.groupBox_6)
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setHorizontalSpacing(10)
        self.gridLayout_12.setVerticalSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.render_as_video_rb = QtGui.QRadioButton(self.widget)
        self.render_as_video_rb.setChecked(True)
        self.render_as_video_rb.setObjectName("render_as_video_rb")
        self.gridLayout_12.addWidget(self.render_as_video_rb, 2, 1, 1, 1)
        self.join_videos_cbx = QtGui.QCheckBox(self.widget)
        self.join_videos_cbx.setObjectName("join_videos_cbx")
        self.gridLayout_12.addWidget(self.join_videos_cbx, 2, 2, 1, 1)
        self.join_images_cbx = QtGui.QCheckBox(self.widget)
        self.join_images_cbx.setEnabled(False)
        self.join_images_cbx.setObjectName("join_images_cbx")
        self.gridLayout_12.addWidget(self.join_images_cbx, 3, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.widget)
        self.label_29.setMinimumSize(QtCore.QSize(50, 0))
        self.label_29.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 2, 0, 2, 1)
        self.render_as_images_rb = QtGui.QRadioButton(self.widget)
        self.render_as_images_rb.setObjectName("render_as_images_rb")
        self.gridLayout_12.addWidget(self.render_as_images_rb, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 1, 0, 1, 1)
        self.persp_res_cbb = QtGui.QComboBox(self.widget)
        self.persp_res_cbb.setObjectName("persp_res_cbb")
        self.persp_res_cbb.addItem("")
        self.persp_res_cbb.addItem("")
        self.gridLayout_12.addWidget(self.persp_res_cbb, 1, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.output_path_le = QtGui.QLineEdit(self.widget)
        self.output_path_le.setObjectName("output_path_le")
        self.horizontalLayout_4.addWidget(self.output_path_le)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 4, 1, 1, 3)
        self.verticalLayout_15.addLayout(self.gridLayout_12)
        self.verticalLayout_14.addWidget(self.widget)
        self.verticalLayout_17.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_3 = QtGui.QWidget(self.groupBox_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.add_frame_stamp_cbx = QtGui.QCheckBox(self.widget_3)
        self.add_frame_stamp_cbx.setChecked(True)
        self.add_frame_stamp_cbx.setObjectName("add_frame_stamp_cbx")
        self.gridLayout_4.addWidget(self.add_frame_stamp_cbx, 0, 0, 1, 1)
        self.stamp_options_btn = QtGui.QPushButton(self.widget_3)
        self.stamp_options_btn.setObjectName("stamp_options_btn")
        self.gridLayout_4.addWidget(self.stamp_options_btn, 0, 1, 1, 1)
        self.preview_frame_btn = QtGui.QPushButton(self.widget_3)
        self.preview_frame_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.preview_frame_btn.setObjectName("preview_frame_btn")
        self.gridLayout_4.addWidget(self.preview_frame_btn, 0, 2, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stamp_mode_shot_rb = QtGui.QRadioButton(self.widget_3)
        self.stamp_mode_shot_rb.setChecked(True)
        self.stamp_mode_shot_rb.setObjectName("stamp_mode_shot_rb")
        self.horizontalLayout_2.addWidget(self.stamp_mode_shot_rb)
        self.stamp_mode_asset_rb = QtGui.QRadioButton(self.widget_3)
        self.stamp_mode_asset_rb.setObjectName("stamp_mode_asset_rb")
        self.horizontalLayout_2.addWidget(self.stamp_mode_asset_rb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_2)
        self.stamp_asset_wd = QtGui.QWidget(self.widget_3)
        self.stamp_asset_wd.setObjectName("stamp_asset_wd")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.stamp_asset_wd)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.asset_fields_grid_ly = QtGui.QGridLayout()
        self.asset_fields_grid_ly.setObjectName("asset_fields_grid_ly")
        self.stamp_asset_project_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_project_le.setReadOnly(True)
        self.stamp_asset_project_le.setObjectName("stamp_asset_project_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_project_le, 0, 1, 1, 1)
        self.stamp_asset_user_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_user_le.setReadOnly(True)
        self.stamp_asset_user_le.setObjectName("stamp_asset_user_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_user_le, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_24.setMinimumSize(QtCore.QSize(50, 0))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.asset_fields_grid_ly.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.asset_fields_grid_ly.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_19.setMinimumSize(QtCore.QSize(50, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.asset_fields_grid_ly.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.asset_fields_grid_ly.addWidget(self.label_22, 1, 0, 1, 1)
        self.stamp_asset_name_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_name_le.setReadOnly(True)
        self.stamp_asset_name_le.setObjectName("stamp_asset_name_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_name_le, 0, 3, 1, 1)
        self.stamp_asset_step_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_step_le.setReadOnly(True)
        self.stamp_asset_step_le.setObjectName("stamp_asset_step_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_step_le, 1, 3, 1, 1)
        self.stamp_asset_task_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_task_le.setReadOnly(True)
        self.stamp_asset_task_le.setObjectName("stamp_asset_task_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_task_le, 2, 3, 1, 1)
        self.stamp_asset_date_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_date_le.setReadOnly(True)
        self.stamp_asset_date_le.setObjectName("stamp_asset_date_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_date_le, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_23.setMinimumSize(QtCore.QSize(50, 0))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.asset_fields_grid_ly.addWidget(self.label_23, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_21.setMinimumSize(QtCore.QSize(50, 0))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.asset_fields_grid_ly.addWidget(self.label_21, 3, 0, 1, 1)
        self.stamp_asset_version_le = QtGui.QLineEdit(self.stamp_asset_wd)
        self.stamp_asset_version_le.setText("")
        self.stamp_asset_version_le.setObjectName("stamp_asset_version_le")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_version_le, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_27.setMinimumSize(QtCore.QSize(50, 0))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.asset_fields_grid_ly.addWidget(self.label_27, 3, 2, 1, 1)
        self.stamp_asset_frame_cbx = QtGui.QCheckBox(self.stamp_asset_wd)
        self.stamp_asset_frame_cbx.setText("")
        self.stamp_asset_frame_cbx.setChecked(True)
        self.stamp_asset_frame_cbx.setObjectName("stamp_asset_frame_cbx")
        self.asset_fields_grid_ly.addWidget(self.stamp_asset_frame_cbx, 3, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.stamp_asset_wd)
        self.label_25.setMinimumSize(QtCore.QSize(50, 0))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.asset_fields_grid_ly.addWidget(self.label_25, 0, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.asset_fields_grid_ly)
        self.verticalLayout_16.addWidget(self.stamp_asset_wd)
        self.stamp_sequence_wd = QtGui.QWidget(self.widget_3)
        self.stamp_sequence_wd.setObjectName("stamp_sequence_wd")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.stamp_sequence_wd)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.shot_fields_grid_ly = QtGui.QGridLayout()
        self.shot_fields_grid_ly.setObjectName("shot_fields_grid_ly")
        self.label_13 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.shot_fields_grid_ly.addWidget(self.label_13, 1, 0, 1, 1)
        self.stamp_squens_user_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_user_le.setReadOnly(True)
        self.stamp_squens_user_le.setObjectName("stamp_squens_user_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_user_le, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.shot_fields_grid_ly.addWidget(self.label_16, 1, 2, 1, 1)
        self.stamp_squens_step_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_step_le.setReadOnly(True)
        self.stamp_squens_step_le.setObjectName("stamp_squens_step_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_step_le, 2, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.shot_fields_grid_ly.addWidget(self.label_14, 2, 0, 1, 1)
        self.stamp_squens_name_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_name_le.setReadOnly(True)
        self.stamp_squens_name_le.setObjectName("stamp_squens_name_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_name_le, 0, 3, 1, 1)
        self.stamp_squens_project_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_project_le.setReadOnly(True)
        self.stamp_squens_project_le.setObjectName("stamp_squens_project_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_project_le, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.shot_fields_grid_ly.addWidget(self.label_7, 0, 0, 1, 1)
        self.stamp_squens_shot_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_shot_le.setReadOnly(True)
        self.stamp_squens_shot_le.setObjectName("stamp_squens_shot_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_shot_le, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_15.setMinimumSize(QtCore.QSize(50, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.shot_fields_grid_ly.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.shot_fields_grid_ly.addWidget(self.label_17, 2, 2, 1, 1)
        self.stamp_squens_date_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_date_le.setReadOnly(True)
        self.stamp_squens_date_le.setObjectName("stamp_squens_date_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_date_le, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_26.setMinimumSize(QtCore.QSize(50, 0))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.shot_fields_grid_ly.addWidget(self.label_26, 3, 0, 1, 1)
        self.stamp_squens_version_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_version_le.setObjectName("stamp_squens_version_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_version_le, 3, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.stamp_sequence_wd)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.shot_fields_grid_ly.addWidget(self.label_18, 3, 2, 1, 1)
        self.stamp_squens_task_le = QtGui.QLineEdit(self.stamp_sequence_wd)
        self.stamp_squens_task_le.setReadOnly(True)
        self.stamp_squens_task_le.setObjectName("stamp_squens_task_le")
        self.shot_fields_grid_ly.addWidget(self.stamp_squens_task_le, 3, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.shot_fields_grid_ly)
        self.verticalLayout_16.addWidget(self.stamp_sequence_wd)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.verticalLayout_17.addWidget(self.groupBox_5)
        self.verticalLayout_17.setStretch(2, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox_7 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_block_btn = QtGui.QPushButton(self.groupBox_7)
        self.add_block_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.add_block_btn.setObjectName("add_block_btn")
        self.horizontalLayout.addWidget(self.add_block_btn)
        self.reload_blocks_btn = QtGui.QPushButton(self.groupBox_7)
        self.reload_blocks_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.reload_blocks_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.reload_blocks_btn.setObjectName("reload_blocks_btn")
        self.horizontalLayout.addWidget(self.reload_blocks_btn)
        self.clear_blocks_btn = QtGui.QPushButton(self.groupBox_7)
        self.clear_blocks_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.clear_blocks_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clear_blocks_btn.setObjectName("clear_blocks_btn")
        self.horizontalLayout.addWidget(self.clear_blocks_btn)
        self.verticalLayout_18.addLayout(self.horizontalLayout)
        self.blocks_ly = QtGui.QVBoxLayout()
        self.blocks_ly.setObjectName("blocks_ly")
        self.verticalLayout_18.addLayout(self.blocks_ly)
        self.verticalLayout_19.addWidget(self.groupBox_7)
        self.afanasy_grp = QtGui.QGroupBox(self.layoutWidget1)
        self.afanasy_grp.setFlat(False)
        self.afanasy_grp.setObjectName("afanasy_grp")
        self.gridLayout_7 = QtGui.QGridLayout(self.afanasy_grp)
        self.gridLayout_7.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_5 = QtGui.QWidget(self.afanasy_grp)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.render_tw = QtGui.QTabWidget(self.widget_5)
        self.render_tw.setObjectName("render_tw")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_31 = QtGui.QLabel(self.tab_6)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 0, 0, 1, 1)
        self.af_job_name_le = QtGui.QLineEdit(self.tab_6)
        self.af_job_name_le.setObjectName("af_job_name_le")
        self.gridLayout_10.addWidget(self.af_job_name_le, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_6)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 1, 0, 1, 1)
        self.af_host_mask_le = QtGui.QLineEdit(self.tab_6)
        self.af_host_mask_le.setObjectName("af_host_mask_le")
        self.gridLayout_10.addWidget(self.af_host_mask_le, 1, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_6)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 2, 0, 1, 1)
        self.af_job_depend_mask_le = QtGui.QLineEdit(self.tab_6)
        self.af_job_depend_mask_le.setObjectName("af_job_depend_mask_le")
        self.gridLayout_10.addWidget(self.af_job_depend_mask_le, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_6)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 3, 0, 1, 1)
        self.af_paused_cbx = QtGui.QCheckBox(self.tab_6)
        self.af_paused_cbx.setText("")
        self.af_paused_cbx.setChecked(True)
        self.af_paused_cbx.setObjectName("af_paused_cbx")
        self.gridLayout_10.addWidget(self.af_paused_cbx, 3, 1, 1, 1)
        self.render_tw.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem5, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem6, 1, 3, 1, 1)
        self.local_paused_cbx = QtGui.QCheckBox(self.tab_7)
        self.local_paused_cbx.setText("")
        self.local_paused_cbx.setObjectName("local_paused_cbx")
        self.gridLayout_13.addWidget(self.local_paused_cbx, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_7)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 0, 0, 1, 1)
        self.post_cmd_cbb = QtGui.QComboBox(self.tab_7)
        self.post_cmd_cbb.setObjectName("post_cmd_cbb")
        self.post_cmd_cbb.addItem("")
        self.post_cmd_cbb.addItem("")
        self.gridLayout_13.addWidget(self.post_cmd_cbb, 1, 1, 1, 1)
        self.render_tw.addTab(self.tab_7, "")
        self.gridLayout_5.addWidget(self.render_tw, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_5, 0, 0, 1, 1)
        self.verticalLayout_19.addWidget(self.afanasy_grp)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.submit_btn = QtGui.QPushButton(self.groupBox_4)
        self.submit_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.submit_btn.setObjectName("submit_btn")
        self.verticalLayout_4.addWidget(self.submit_btn)
        self.verticalLayout_19.addWidget(self.groupBox_4)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.splitter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1214, 21))
        self.menubar.setObjectName("menubar")
        self.menuShotgun_Setup = QtGui.QMenu(self.menubar)
        self.menuShotgun_Setup.setObjectName("menuShotgun_Setup")
        self.menuPresets = QtGui.QMenu(self.menubar)
        self.menuPresets.setObjectName("menuPresets")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionShotgin_Setup = QtGui.QAction(MainWindow)
        self.actionShotgin_Setup.setObjectName("actionShotgin_Setup")
        self.actionCGRU_Setup = QtGui.QAction(MainWindow)
        self.actionCGRU_Setup.setObjectName("actionCGRU_Setup")
        self.actionSubmitter_Setup = QtGui.QAction(MainWindow)
        self.actionSubmitter_Setup.setObjectName("actionSubmitter_Setup")
        self.open_folder_act = QtGui.QAction(MainWindow)
        self.open_folder_act.setObjectName("open_folder_act")
        self.save_to_preset_act = QtGui.QAction(MainWindow)
        self.save_to_preset_act.setObjectName("save_to_preset_act")
        self.cleanup_scene_act = QtGui.QAction(MainWindow)
        self.cleanup_scene_act.setObjectName("cleanup_scene_act")
        self.actionCollapse_All = QtGui.QAction(MainWindow)
        self.actionCollapse_All.setObjectName("actionCollapse_All")
        self.actionExpand_All = QtGui.QAction(MainWindow)
        self.actionExpand_All.setObjectName("actionExpand_All")
        self.menuShotgun_Setup.addAction(self.cleanup_scene_act)
        self.menuPresets.addAction(self.open_folder_act)
        self.menubar.addAction(self.menuShotgun_Setup.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPresets.menuAction())

        self.retranslateUi(MainWindow)
        self.cameras_tab.setCurrentIndex(0)
        self.renderer_tab_tbw.setCurrentIndex(1)
        self.render_tw.setCurrentIndex(0)
        QtCore.QObject.connect(self.ai_use_ground_plane_cbx, QtCore.SIGNAL("clicked(bool)"), self.ai_ground_plane_texture_cbb.setEnabled)
        QtCore.QObject.connect(self.ogl_use_ground_plane_cbx, QtCore.SIGNAL("clicked(bool)"), self.ogl_ground_plane_texture_cbb.setEnabled)
        QtCore.QObject.connect(self.add_frame_stamp_cbx, QtCore.SIGNAL("clicked(bool)"), self.stamp_options_btn.setEnabled)
        QtCore.QObject.connect(self.add_frame_stamp_cbx, QtCore.SIGNAL("clicked(bool)"), self.stamp_sequence_wd.setEnabled)
        QtCore.QObject.connect(self.render_as_video_rb, QtCore.SIGNAL("clicked(bool)"), self.join_videos_cbx.setEnabled)
        QtCore.QObject.connect(self.render_as_video_rb, QtCore.SIGNAL("toggled(bool)"), self.join_videos_cbx.setEnabled)
        QtCore.QObject.connect(self.groupBox_2, QtCore.SIGNAL("toggled(bool)"), self.renderer_tab_tbw.setVisible)
        QtCore.QObject.connect(self.groupBox_6, QtCore.SIGNAL("toggled(bool)"), self.widget.setVisible)
        QtCore.QObject.connect(self.groupBox_3, QtCore.SIGNAL("toggled(bool)"), self.widget_2.setVisible)
        QtCore.QObject.connect(self.groupBox, QtCore.SIGNAL("toggled(bool)"), self.cameras_tab.setVisible)
        QtCore.QObject.connect(self.add_frame_stamp_cbx, QtCore.SIGNAL("clicked(bool)"), self.stamp_asset_wd.setEnabled)
        QtCore.QObject.connect(self.groupBox_5, QtCore.SIGNAL("toggled(bool)"), self.widget_3.setVisible)
        QtCore.QObject.connect(self.afanasy_grp, QtCore.SIGNAL("toggled(bool)"), self.widget_5.setVisible)
        QtCore.QObject.connect(self.stamp_mode_shot_rb, QtCore.SIGNAL("toggled(bool)"), self.stamp_asset_wd.setHidden)
        QtCore.QObject.connect(self.stamp_mode_shot_rb, QtCore.SIGNAL("toggled(bool)"), self.stamp_sequence_wd.setVisible)
        QtCore.QObject.connect(self.render_as_images_rb, QtCore.SIGNAL("toggled(bool)"), self.join_images_cbx.setEnabled)
        QtCore.QObject.connect(self.add_light_preset_cbx, QtCore.SIGNAL("toggled(bool)"), self.light_setup_ogl_grp.setEnabled)
        QtCore.QObject.connect(self.add_light_preset_cbx, QtCore.SIGNAL("toggled(bool)"), self.light_setup_ai_grp.setEnabled)
        QtCore.QObject.connect(self.add_frame_stamp_cbx, QtCore.SIGNAL("toggled(bool)"), self.stamp_mode_asset_rb.setEnabled)
        QtCore.QObject.connect(self.add_frame_stamp_cbx, QtCore.SIGNAL("toggled(bool)"), self.stamp_mode_shot_rb.setEnabled)
        QtCore.QObject.connect(self.stamp_asset_project_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_project_le.setText)
        QtCore.QObject.connect(self.stamp_asset_user_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_user_le.setText)
        QtCore.QObject.connect(self.stamp_asset_date_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_date_le.setText)
        QtCore.QObject.connect(self.stamp_asset_version_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_version_le.setText)
        QtCore.QObject.connect(self.stamp_asset_task_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_task_le.setText)
        QtCore.QObject.connect(self.stamp_asset_step_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_squens_step_le.setText)
        QtCore.QObject.connect(self.stamp_squens_project_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_project_le.setText)
        QtCore.QObject.connect(self.stamp_squens_user_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_user_le.setText)
        QtCore.QObject.connect(self.stamp_squens_date_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_date_le.setText)
        QtCore.QObject.connect(self.stamp_squens_version_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_version_le.setText)
        QtCore.QObject.connect(self.stamp_squens_step_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_step_le.setText)
        QtCore.QObject.connect(self.stamp_squens_task_le, QtCore.SIGNAL("textChanged(QString)"), self.stamp_asset_task_le.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.add_objects_btn)
        MainWindow.setTabOrder(self.add_objects_btn, self.remove_objects_btn)
        MainWindow.setTabOrder(self.remove_objects_btn, self.select_objects_btn)
        MainWindow.setTabOrder(self.select_objects_btn, self.clear_objects_btn)
        MainWindow.setTabOrder(self.clear_objects_btn, self.cameras_tab)
        MainWindow.setTabOrder(self.cameras_tab, self.create_new_camera_btn)
        MainWindow.setTabOrder(self.create_new_camera_btn, self.reload_cameras_btn)
        MainWindow.setTabOrder(self.reload_cameras_btn, self.render_camera_cbb)
        MainWindow.setTabOrder(self.render_camera_cbb, self.range_start_sbx)
        MainWindow.setTabOrder(self.range_start_sbx, self.range_end_sbx)
        MainWindow.setTabOrder(self.range_end_sbx, self.range_from_btn)
        MainWindow.setTabOrder(self.range_from_btn, self.open_sequence_editor_btn)
        MainWindow.setTabOrder(self.open_sequence_editor_btn, self.sequ_start_spx)
        MainWindow.setTabOrder(self.sequ_start_spx, self.sequ_end_spx)
        MainWindow.setTabOrder(self.sequ_end_spx, self.sequencer_rang_btn)
        MainWindow.setTabOrder(self.sequencer_rang_btn, self.add_light_preset_cbx)
        MainWindow.setTabOrder(self.add_light_preset_cbx, self.renderer_tab_tbw)
        MainWindow.setTabOrder(self.renderer_tab_tbw, self.reload_rig_btn1)
        MainWindow.setTabOrder(self.reload_rig_btn1, self.ai_scene_preset_cbb)
        MainWindow.setTabOrder(self.ai_scene_preset_cbb, self.ai_render_background_cbx)
        MainWindow.setTabOrder(self.ai_render_background_cbx, self.ai_use_ground_plane_cbx)
        MainWindow.setTabOrder(self.ai_use_ground_plane_cbx, self.ai_ground_plane_texture_cbb)
        MainWindow.setTabOrder(self.ai_ground_plane_texture_cbb, self.reload_rig_btn2)
        MainWindow.setTabOrder(self.reload_rig_btn2, self.ogl_scene_preset_cbb)
        MainWindow.setTabOrder(self.ogl_scene_preset_cbb, self.ogl_use_ground_plane_cbx)
        MainWindow.setTabOrder(self.ogl_use_ground_plane_cbx, self.ogl_ground_plane_texture_cbb)
        MainWindow.setTabOrder(self.ogl_ground_plane_texture_cbb, self.persp_res_cbb)
        MainWindow.setTabOrder(self.persp_res_cbb, self.render_as_video_rb)
        MainWindow.setTabOrder(self.render_as_video_rb, self.render_as_images_rb)
        MainWindow.setTabOrder(self.render_as_images_rb, self.join_videos_cbx)
        MainWindow.setTabOrder(self.join_videos_cbx, self.join_images_cbx)
        MainWindow.setTabOrder(self.join_images_cbx, self.output_path_le)
        MainWindow.setTabOrder(self.output_path_le, self.add_frame_stamp_cbx)
        MainWindow.setTabOrder(self.add_frame_stamp_cbx, self.stamp_options_btn)
        MainWindow.setTabOrder(self.stamp_options_btn, self.preview_frame_btn)
        MainWindow.setTabOrder(self.preview_frame_btn, self.stamp_mode_shot_rb)
        MainWindow.setTabOrder(self.stamp_mode_shot_rb, self.stamp_mode_asset_rb)
        MainWindow.setTabOrder(self.stamp_mode_asset_rb, self.stamp_asset_project_le)
        MainWindow.setTabOrder(self.stamp_asset_project_le, self.stamp_asset_user_le)
        MainWindow.setTabOrder(self.stamp_asset_user_le, self.stamp_asset_date_le)
        MainWindow.setTabOrder(self.stamp_asset_date_le, self.stamp_asset_version_le)
        MainWindow.setTabOrder(self.stamp_asset_version_le, self.stamp_asset_name_le)
        MainWindow.setTabOrder(self.stamp_asset_name_le, self.stamp_asset_step_le)
        MainWindow.setTabOrder(self.stamp_asset_step_le, self.stamp_asset_task_le)
        MainWindow.setTabOrder(self.stamp_asset_task_le, self.stamp_asset_frame_cbx)
        MainWindow.setTabOrder(self.stamp_asset_frame_cbx, self.stamp_squens_project_le)
        MainWindow.setTabOrder(self.stamp_squens_project_le, self.stamp_squens_user_le)
        MainWindow.setTabOrder(self.stamp_squens_user_le, self.stamp_squens_date_le)
        MainWindow.setTabOrder(self.stamp_squens_date_le, self.stamp_squens_version_le)
        MainWindow.setTabOrder(self.stamp_squens_version_le, self.stamp_squens_name_le)
        MainWindow.setTabOrder(self.stamp_squens_name_le, self.stamp_squens_shot_le)
        MainWindow.setTabOrder(self.stamp_squens_shot_le, self.stamp_squens_step_le)
        MainWindow.setTabOrder(self.stamp_squens_step_le, self.stamp_squens_task_le)
        MainWindow.setTabOrder(self.stamp_squens_task_le, self.add_block_btn)
        MainWindow.setTabOrder(self.add_block_btn, self.reload_blocks_btn)
        MainWindow.setTabOrder(self.reload_blocks_btn, self.clear_blocks_btn)
        MainWindow.setTabOrder(self.clear_blocks_btn, self.render_tw)
        MainWindow.setTabOrder(self.render_tw, self.af_job_name_le)
        MainWindow.setTabOrder(self.af_job_name_le, self.af_host_mask_le)
        MainWindow.setTabOrder(self.af_host_mask_le, self.af_job_depend_mask_le)
        MainWindow.setTabOrder(self.af_job_depend_mask_le, self.af_paused_cbx)
        MainWindow.setTabOrder(self.af_paused_cbx, self.submit_btn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Asset Preview Submitter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Setup Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.add_objects_btn.setText(QtGui.QApplication.translate("MainWindow", "Add Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_objects_btn.setText(QtGui.QApplication.translate("MainWindow", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.select_objects_btn.setText(QtGui.QApplication.translate("MainWindow", "Select Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_objects_btn.setText(QtGui.QApplication.translate("MainWindow", "Clear Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Select Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.render_camera_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.range_from_btn.setText(QtGui.QApplication.translate("MainWindow", "Set From ...", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_cameras_btn.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Reload cameras</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_cameras_btn.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.create_new_camera_btn.setText(QtGui.QApplication.translate("MainWindow", "New Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cameras_tab.setTabText(self.cameras_tab.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "From Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sequencer Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Sequencer End", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencer_rang_btn.setText(QtGui.QApplication.translate("MainWindow", "Full Range", None, QtGui.QApplication.UnicodeUTF8))
        self.open_sequence_editor_btn.setText(QtGui.QApplication.translate("MainWindow", "Sequence Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.cameras_tab.setTabText(self.cameras_tab.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "From Sequencer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Setup Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.add_light_preset_cbx.setText(QtGui.QApplication.translate("MainWindow", "Add Ligth Preset", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_rig_btn1.setText(QtGui.QApplication.translate("MainWindow", "Rebuild", None, QtGui.QApplication.UnicodeUTF8))
        self.light_setup_ai_grp.setTitle(QtGui.QApplication.translate("MainWindow", "Light Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Light Presets:", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_use_ground_plane_cbx.setText(QtGui.QApplication.translate("MainWindow", "Ground Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_scene_preset_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Outdor", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_scene_preset_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Indor", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_scene_preset_cbb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_scene_preset_cbb.setItemText(3, QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_render_background_cbx.setText(QtGui.QApplication.translate("MainWindow", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_ground_plane_texture_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_ground_plane_texture_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Checher", None, QtGui.QApplication.UnicodeUTF8))
        self.ai_ground_plane_texture_cbb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.renderer_tab_tbw.setTabText(self.renderer_tab_tbw.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Arnold", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_rig_btn2.setText(QtGui.QApplication.translate("MainWindow", "Rebuild", None, QtGui.QApplication.UnicodeUTF8))
        self.light_setup_ogl_grp.setTitle(QtGui.QApplication.translate("MainWindow", "Light Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Light Presets:", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_scene_preset_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Outdor", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_scene_preset_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_use_ground_plane_cbx.setText(QtGui.QApplication.translate("MainWindow", "Ground Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_ground_plane_texture_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_ground_plane_texture_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Checher", None, QtGui.QApplication.UnicodeUTF8))
        self.ogl_ground_plane_texture_cbb.setItemText(2, QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.renderer_tab_tbw.setTabText(self.renderer_tab_tbw.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "OpenGL", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Output Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.render_as_video_rb.setText(QtGui.QApplication.translate("MainWindow", "Video MP4", None, QtGui.QApplication.UnicodeUTF8))
        self.join_videos_cbx.setText(QtGui.QApplication.translate("MainWindow", "Join layers to single video", None, QtGui.QApplication.UnicodeUTF8))
        self.join_images_cbx.setText(QtGui.QApplication.translate("MainWindow", "Join to single board", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Render as", None, QtGui.QApplication.UnicodeUTF8))
        self.render_as_images_rb.setText(QtGui.QApplication.translate("MainWindow", "Images PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", " Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.persp_res_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "1280x720", None, QtGui.QApplication.UnicodeUTF8))
        self.persp_res_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "649x360", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Output Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", " Frame Stamp And Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.add_frame_stamp_cbx.setText(QtGui.QApplication.translate("MainWindow", "Add Frame Stamp", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_options_btn.setText(QtGui.QApplication.translate("MainWindow", "Stamp Options", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_frame_btn.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_mode_shot_rb.setText(QtGui.QApplication.translate("MainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_mode_asset_rb.setText(QtGui.QApplication.translate("MainWindow", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_project_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Project >", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_user_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< User >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_name_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Asst name >", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_step_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Step name >", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_task_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Task name >", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_date_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< ##.##.#### ##:## >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_asset_version_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< ### >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_user_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< User >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_step_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Step name >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_name_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< EP### >", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_project_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Project >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_shot_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< sh-#### >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_date_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< ##.##.#### ##:## >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_version_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< ### >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.stamp_squens_task_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "< Task name >", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Render Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.add_block_btn.setText(QtGui.QApplication.translate("MainWindow", "Add Render Block", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_blocks_btn.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_blocks_btn.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.afanasy_grp.setTitle(QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Job Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Host Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Job Dependency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Paused", None, QtGui.QApplication.UnicodeUTF8))
        self.render_tw.setTabText(self.render_tw.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Afanasy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Post Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Paused", None, QtGui.QApplication.UnicodeUTF8))
        self.post_cmd_cbb.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.post_cmd_cbb.setItemText(1, QtGui.QApplication.translate("MainWindow", "Open Result Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.render_tw.setTabText(self.render_tw.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_btn.setText(QtGui.QApplication.translate("MainWindow", "Submit Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShotgun_Setup.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPresets.setTitle(QtGui.QApplication.translate("MainWindow", "Presets", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShotgin_Setup.setText(QtGui.QApplication.translate("MainWindow", "Shotgun Setup...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCGRU_Setup.setText(QtGui.QApplication.translate("MainWindow", "CGRU Setup...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubmitter_Setup.setText(QtGui.QApplication.translate("MainWindow", "Submitter Setup...", None, QtGui.QApplication.UnicodeUTF8))
        self.open_folder_act.setText(QtGui.QApplication.translate("MainWindow", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.save_to_preset_act.setText(QtGui.QApplication.translate("MainWindow", "Save Selected ", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanup_scene_act.setText(QtGui.QApplication.translate("MainWindow", "Cleanup and exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapse_All.setText(QtGui.QApplication.translate("MainWindow", "Collapse All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpand_All.setText(QtGui.QApplication.translate("MainWindow", "Expand All", None, QtGui.QApplication.UnicodeUTF8))

